name = "poppyjeans-api"
main = "src/index.js"
compatibility_date = "2024-04-08"

[dev]
port = 8788


[[d1_databases]]
binding = "DB"
database_name = "poppyjeans-db"
database_id = "c203d4ec-5494-462f-9e79-81bf81d9e5bb"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "poppyjeans-images"

[vars]
PUBLIC_IMAGES_URL = "https://images.poppyjeans.cl"
TBK_API_KEY_ID = "597053091377"
TBK_API_KEY_SECRET = "1ce60548-8540-4e82-960f-44851e27ca21"
TBK_BASE_URL = "https://webpay3g.transbank.cl/rswebpaytransaction/api/webpay/v1.2/transactions"

routes = [
  { pattern = "api.poppyjeans.cl", custom_domain = true }
]